# Generated by Django 4.1 on 2024-07-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="temp@example.com", max_length=250, unique=True
            ),
            preserve_default=False,
        ),
    ]
